### ISSUE TITLE
Fix configuration instruction according to IDEA 2018.2.3+ behaviour

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/KotlinAsFirst-Coursera#2]

**Comment by mglukhikh** [comment]
See https://www.coursera.org/teach/vvedenie-v-yazyk-kotlin/content/edit/supplement/sDb3P?versionId=ZTBpqpDXEeiW-QopTLEf_g

**Comment by Arirokk** [comment]
I can't see it
